# Generated by Django 4.1.5 on 2023-02-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venuemile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
            ],
        ),
    ]
