# Generated by Django 4.1.5 on 2023-02-15 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0003_registration2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.DeleteModel(
            name='registration2',
        ),
    ]
