# Generated by Django 4.1.5 on 2023-02-15 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0005_register_registration2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.DeleteModel(
            name='registration2',
        ),
    ]
