# Generated by Django 4.1.5 on 2023-02-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0007_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('confirmpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
