# Generated by Django 4.1.5 on 2023-02-24 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0010_aud1book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='aud1book',
        ),
        migrations.DeleteModel(
            name='venuemile',
        ),
    ]
