# Generated by Django 4.1.5 on 2023-02-24 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0012_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
