# Generated by Django 4.1.5 on 2023-03-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0018_remove_test_end_time_remove_test_start_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
