# Generated by Django 4.1.5 on 2023-04-18 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0021_convention'),
    ]

    operations = [
        migrations.DeleteModel(
            name='convention',
        ),
    ]
