# Generated by Django 4.1.5 on 2023-04-19 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0027_remove_convention_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='convention',
        ),
    ]
