# Generated by Django 4.1.5 on 2023-04-20 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0029_convention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convention',
            name='gallery',
        ),
    ]
