# Generated by Django 4.1.5 on 2023-04-22 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0030_remove_convention_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='convention_gallery')),
                ('convention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='evmapp.convention')),
            ],
        ),
    ]
