# Generated by Django 4.1.5 on 2023-04-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0033_cateringmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='decortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='convention',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
