# Generated by Django 4.1.5 on 2023-04-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0034_decortion_alter_convention_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='decortion',
        ),
    ]
