# Generated by Django 4.1.5 on 2023-04-29 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0037_photography'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='convention_gallery')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evmapp.photography')),
            ],
        ),
    ]
