# Generated by Django 4.1.5 on 2023-04-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0039_accommodaton_alter_previousworks_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='accommodaton',
        ),
    ]
