# Generated by Django 4.1.5 on 2023-04-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0040_delete_accommodaton'),
    ]

    operations = [
        migrations.CreateModel(
            name='accommodaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=25)),
                ('restaurant', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('campfire', models.BooleanField(default=False)),
                ('fitness_center', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('place', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
            ],
        ),
    ]
