# Generated by Django 4.1.5 on 2023-04-29 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0041_accommodaton'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evmapp.accommodaton')),
            ],
        ),
    ]
