# Generated by Django 4.1.5 on 2023-05-03 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0045_alter_transportation_bus_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='transportation',
        ),
    ]
