# Generated by Django 4.1.5 on 2023-05-12 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0047_transportation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='accommodaton',
            new_name='accommodation',
        ),
        migrations.RenameModel(
            old_name='decortion',
            new_name='decoration',
        ),
    ]
