# Generated by Django 4.1.5 on 2023-05-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0049_alter_galleryimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
