# Generated by Django 4.1.5 on 2023-05-15 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0052_admin_alter_cateringmenu_catering_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='confirmpassword',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='phone',
        ),
    ]
