# Generated by Django 4.1.5 on 2023-05-15 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0053_remove_admin_confirmpassword_remove_admin_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convention_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('6\\d{10}$', 'Enter a valid phone number.')])),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
