# Generated by Django 4.1.5 on 2023-05-16 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0054_convention_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convention_Booking',
        ),
    ]
