# Generated by Django 4.1.5 on 2023-05-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0058_rename_phone_convention_booking_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Convention_Booking',
        ),
    ]
