# Generated by Django 4.1.5 on 2023-05-25 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0066_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transportation_Booking',
        ),
    ]
