# Generated by Django 4.1.5 on 2023-05-25 06:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0067_delete_transportation_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation_Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid phone number.')])),
                ('date', models.DateField()),
                ('message', models.TextField()),
                ('location', models.TextField()),
                ('travels_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evmapp.transportation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evmapp.user')),
            ],
        ),
    ]
