# Generated by Django 4.1.5 on 2023-05-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0070_remove_galleryimage_convention_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='convention',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='convention',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='evmapp.convention'),
        ),
    ]
