# Generated by Django 4.1.5 on 2023-05-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0071_remove_galleryimage_convention_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
