# Generated by Django 4.1.5 on 2023-05-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0072_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convention',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
