# Generated by Django 4.1.5 on 2023-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0073_alter_convention_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='catering',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='decoration',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='entertainment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photography',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transportation',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
