# Generated by Django 4.1.5 on 2023-05-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0074_alter_accommodation_name_alter_catering_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catering',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='photography',
            name='location',
            field=models.CharField(max_length=1000),
        ),
    ]
