# Generated by Django 4.1.5 on 2023-06-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evmapp', '0076_remove_cateringbooking_catering_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photography_booking',
            name='type',
        ),
    ]
